#!/usr/bin/with-contenv bash
###############################################
#
#  Run daily tasks
#
###############################################

sleep 20

while true; do
  echo "Running daily tasks."
  python3 -m pip install -U repoupdater addonupdater
  repoupdater --token $GHTOKEN --repo ludeeus/custom-component-store --pip --apk --pull-request

  echo "Daily tasks done, sleeping..."
  sleep 86400
done