#!/usr/bin/with-contenv bash
###############################################
#
#  Run daily tasks
#
###############################################

sleep 20

while true; do
  echo "Running daily tasks."
  python3 -m pip install -U repoupdater addonupdater

  repoupdater --token $GHTOKEN --repo ludeeus/custom-component-store --pip --apk --pull_request --apk_version 3.9 --docker_path docker
  repoupdater --token $GHTOKEN --repo ludeeus/tasks --apk --pull_request --apk_version 3.9

  addonupdater --token $GHTOKEN --apk_version 3.9 --pull_request --addon tautulli
  addonupdater --token $GHTOKEN --apk_version 3.9 --pull_request --addon phlex
  addonupdater --token $GHTOKEN --apk_version 3.9 --pull_request --addon sqlite-web
  addonupdater --token $GHTOKEN --apk_version 3.9 --pull_request --addon magicmirror
  addonupdater --token $GHTOKEN --apk_version 3.9 --pull_request --addon mqtt

  echo "Daily tasks done, sleeping..."
  sleep 86400
done
