#!/usr/bin/with-contenv bash
###############################################
#
#  Run daily tasks
#
###############################################

while true; do
  echo "Running hourly tasks."
  python3 -m pip install -U customjson
  customjson --token $GHTOKEN --mode component
  customjson --token $GHTOKEN --mode card
  sleep 3600
done