#!/usr/bin/with-contenv bash
###############################################
#
#  Run daily tasks
#
###############################################

sleep 40

while true; do
  echo "Running 10min tasks."

  echo "10min tasks done, sleeping..."
  sleep 600
done